name: Fetch and Save Cloud API Spec

on:
  workflow_dispatch:  # Allows manual trigger of the workflow
  repository_dispatch:  # Allows other repositories to trigger this workflow
    types: [trigger-cloud-api-docs]

jobs:
  fetch-and-save-cloud-api-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: redpanda-docs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd ./redpanda-docs/scripts/get-api-specs
          npm install

      - name: Run Script and Save Output
        run: node ./redpanda-docs/scripts/get-api-specs/get-cloud-api-spec.js > ./redpanda-docs/cloud-api.yaml
        env:
          VBOT_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout API Branch
        uses: actions/checkout@v4
        with:
          ref: api  # Checking out the api branch to save the generated file
          path: redpanda-docs-api
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Generated File to API Branch
        run: mv ./redpanda-docs/cloud-api.yaml ./redpanda-docs-api/modules/ROOT/attachments/cloud-api.yaml

      - name: Commit and Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "auto-docs: Update Cloud API spec"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-branch-api  # Branch that the PR will be created from
          title: "auto-docs: Update Cloud API spec"
          body: "This PR updates the OpenAPI spec file for the Cloud API."
          labels: auto-docs
