name: Update @redpanda-data/docs-extensions-and-macros

on:
  schedule:
    - cron: '0 8 * * 4'
  workflow_dispatch: # Allows the workflow to be triggered manually
  repository_dispatch: # Allows the workflow to be triggered by another repository
    types: [trigger-update]

jobs:
  update-dependency:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [main, v/24.1, v/23.3, api] # Add your predefined base branches here

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Update @redpanda-data/docs-extensions-and-macros
        run: npm update @redpanda-data/docs-extensions-and-macros

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-branch-${{ matrix.branch }}
          git add package.json package-lock.json
          git commit -m "Update @redpanda-data/docs-extensions-and-macros"
        env:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}

      - name: Push changes and create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update @redpanda-data/docs-extensions-and-macros"
          git-token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          branch: update-branch-${{ matrix.branch }}
          base: ${{ matrix.branch }}
          title: "auto-docs: Update extensions on ${{ matrix.branch }}"
          body: "This PR updates the @redpanda-data/docs-extensions-and-macros package on the ${{ matrix.branch }} branch."
          labels: auto-docs
          reviewers: JakeSCahill, Deflaimun
